version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/ApplicationCore"
    schedule:
      interval: "daily"                    
      time: "10:30"                        
      timezone: "Europe/Berlin"
  - package-ecosystem: "nuget"
    directory: "/src/ApplicationCore.Tests"
    schedule:
      interval: "daily"                    
      time: "10:30"                        
      timezone: "Europe/Berlin"
  - package-ecosystem: "nuget"
    directory: "/src/GUI"
    schedule:
      interval: "daily"                    
      time: "10:30"                        
      timezone: "Europe/Berlin"
