version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/ApplicationCore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/ApplicationCore.Tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/GUI"
    schedule:
      interval: "weekly"
