# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/ApplicationCore.Tests/ApplicationCore.Tests.csproj
    - name: Build ApplicationCore and Tests
      run: dotnet build ./src/ApplicationCore.Tests/ApplicationCore.Tests.csproj --no-restore
    - name: Run Tests
      run: dotnet test ./src/ApplicationCore.Tests/ApplicationCore.Tests.csproj --no-build --verbosity normal
